root: results/water_400
run_name: water 
seed: 123
dataset_seed: 456                                                                          
append: true                                                                     
default_dtype: float32                                                            
allow_tf32: false                                                                 
# device:  cuda                                                                     

model_builders:
 - SimpleIrrepsConfig
 - EnergyModel
 - PerSpeciesRescale
 - ForceOutput
 - RescaleEnergyEtc

# network
r_max: 4.5                                                                     
num_layers: 6                                                                    

l_max: 1                                                                          
parity: true                                                                      
num_features: 32                                                                 

nonlinearity_type: gate                                                           
resnet: false                                                                     
nonlinearity_scalars:
  e: silu
  o: tanh

nonlinearity_gates:
  e: silu
  o: tanh

# radial network basis
num_basis: 8                                                                     
BesselBasis_trainable: true                                                       
PolynomialCutoff_p: 6                                                             
# radial network
invariant_layers: 2                                                               
invariant_neurons: 64                                                             
avg_num_neighbors: auto                                                           
use_sc: true                                                                     
dataset: npz
dataset_file_name: water.npz
key_mapping:
  z: atomic_numbers
  E: total_energy
  F: forces
  R: pos
  pbc: pbc
  cell: cell
npz_fixed_field_keys:
  - atomic_numbers
  - cell
  - pbc

chemical_symbols:
 - H
 - O
#wandb: true
#wandb_project: c7_big_cell

verbose: info                                                                      
log_batch_freq: 1                                                                  
log_epoch_freq: 1                                                                  
save_checkpoint_freq: -1                                                           
save_ema_checkpoint_freq: -1                                                       

# training
n_train: 400
n_val: 100
learning_rate: 0.0005 
batch_size: 1                                                                      
max_epochs: 60                                                                    
train_val_split: random                                                            
shuffle: true                                                                      
metrics_key: validation_loss                                                        
use_ema: true                                                                      
ema_decay: 0.99                                                                    
ema_use_num_updates: true                                                          
report_init_validation: true                                                      


early_stopping_patiences:                                                          
  validation_loss: 250

early_stopping_delta:                                                              
  validation_loss: 0.005

early_stopping_cumulative_delta: false                                            

early_stopping_lower_bounds:                                                       
  LR: 1.0e-5

early_stopping_upper_bounds:                                                       
  wall: 1.0e+100
                                                          
# loss function
loss_coeffs:                                                                       
  forces: 1                                                                     
  total_energy:                                                                    
    - 1
    - PerAtomMSELoss



# output metrics
metrics_components:
  - - forces                               
    - mae
  - - forces
    - rmse                                 
    - PerSpecies: True                     
      report_per_component: False          
  - - forces
    - mae
    - PerSpecies: True
      report_per_component: False
  - - total_energy
    - mae
    - PerAtom: True                        

optimizer_name: Adam                                                               
optimizer_amsgrad: true
optimizer_betas: !!python/tuple
  - 0.9
  - 0.999
optimizer_eps: 1.0e-08
optimizer_weight_decay: 0

max_gradient_norm: null


lr_scheduler_name: ReduceLROnPlateau
lr_scheduler_patience: 100
lr_scheduler_factor: 0.5


per_species_rescale_scales_trainable: false

per_species_rescale_shifts_trainable: false

per_species_rescale_shifts: dataset_per_atom_total_energy_mean
per_species_rescale_scales: dataset_forces_rms
